In [123]:
import networkx as nx
import pandas as pd
import json
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV

In [195]:
target=pd.read_csv("./twitch/FR/musae_FR_target.csv")

In [125]:
edges=pd.read_csv("./twitch/FR/musae_FR_edges.csv")

In [126]:
graph_path="./twitch/FR/musae_FR_features.json"

In [147]:

# load JSON data from file
with open(graph_path, 'r') as f:
    data = json.load(f)

# create new NetworkX graph
G = nx.Graph()


G = nx.from_dict_of_lists(data)

# visualize the graph
#nx.draw(G, with_labels=True)

mat=nx.adjacency_matrix(G).toarray()

In [150]:
G.number_of_edges()

128983

In [151]:
G.number_of_nodes()

8824

In [153]:
print('Average degree: ', sum(dict(G.degree()).values()) / len(G))

Average degree:  29.23458748866727


In [161]:
G.degree

DegreeView({'3032': 11, '4032': 29, '3945': 21, '949': 33, '5137': 18, '400': 15, '1803': 16, '2468': 52, '289': 12, '5687': 18, '2811': 14, '1689': 16, '6077': 16, '3324': 17, '6357': 13, '5905': 21, '5571': 19, '1968': 18, '3636': 13, '1769': 15, '349': 18, '1983': 33, '3867': 18, '1234': 17, '137': 16, '5310': 28, '4677': 18, '4619': 26, '2481': 13, '1508': 15, '2901': 23, '1068': 20, '5693': 17, '6291': 22, '5250': 20, '2475': 18, '4047': 50, '3377': 18, '4428': 18, '3167': 13, '4648': 30, '6377': 33, '790': 24, '3321': 22, '1619': 21, '3576': 19, '1295': 17, '4163': 22, '5531': 21, '4852': 13, '4667': 14, '181': 13, '5283': 24, '3055': 15, '1434': 24, '1518': 33, '3744': 15, '1136': 16, '1947': 18, '3088': 30, '1022': 13, '6133': 19, '5929': 11, '3200': 15, '5184': 13, '2554': 10, '598': 18, '3257': 12, '3403': 17, '3812': 21, '5143': 33, '3242': 17, '2299': 16, '5803': 11, '1134': 17, '4770': 13, '2208': 14, '1595': 17, '464': 17, '3689': 15, '1972': 32, '4525': 8, '5150': 21, '3

In [162]:
degrees = dict(G.degree())
max_degree_node = max(degrees, key=degrees.get)
print("Node with maximum degree:", max_degree_node)


Node with maximum degree: 920


In [157]:
degrees = list(dict(G.degree()).values())
print(max(degrees))

6139


In [164]:
degree_dict = dict(G.degree(G.nodes()))
sorted_degree = sorted(degree_dict.items(), key=lambda x: x[1], reverse=True)
top_10_nodes = [x[0] for x in sorted_degree[:10]]


In [165]:
top_10_nodes

[920, 224, 569, 861, 810, 2645, 653, 3097, 2424, 2737]

In [128]:
mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [129]:
target

id  days  mature  views  partner  new_id
0     150417538   577    True    775    False    4867
1     125723704   861    True   2585    False    3692
2     155971814   523   False   1566    False    3816
3      35832890  2234   False   9713    False     416
4      46787750  1896    True  44529    False    4502
...         ...   ...     ...    ...      ...     ...
6546   29196284  2061   False   3822    False    6546
6547  124327806   880    True  30313    False    2392
6548  144229380   640    True   5022    False     391
6549  131423064   736   False   2658    False    2793
6550   45419243  1929    True   3743    False    1092

[6551 rows x 6 columns]

In [163]:
target.loc[target["new_id"]]

id  days  mature  views  partner  new_id
5937  131074365   802      -1  43451       -1     920

In [169]:
 target[target[["new_id"]].isin(top_10_nodes).any(axis=1)]

id  days  mature   views  partner  new_id
386    28629460  2415      -1  868026        1    2645
1167  118572706   927       1    6027       -1     653
2178  103455447  1107      -1   24639       -1    2737
3629   93603866  1215      -1    6533       -1     810
3774   84876863  1312       1   71312       -1    3097
4805   77988439  1386      -1   10038       -1     224
4822   43767764  1937      -1     638       -1    2424
5376  150308303   568      -1    1351       -1     569
5540  160303272   467      -1    1259       -1     861
5937  131074365   802      -1   43451       -1     920

In [170]:
top_10_nodes_with_maximum_degree

[920, 224, 569, 861, 810, 2645, 653, 3097, 2424, 2737]

In [130]:
#Algorithme 1

In [196]:
def binary(x):
    if x==True:
        return 1
    else:
        return -1

In [195]:
target=pd.read_csv("./twitch/FR/musae_FR_target.csv")

target["mature"]=target["mature"].apply(binary)

target["partner"]=target["partner"].apply(binary)

In [134]:
unlabeled,labeled=train_test_split(target,test_size=0.1)

In [135]:
labeled

id  days  mature   views  partner  new_id
1112   62277047  1618      -1   16939       -1     562
1739   45619043  1333      -1     171       -1    2381
4417  154202330   538      -1    9245       -1    4906
6010   88424832  1276       1   25106       -1     138
3108   93641700  1213       1    8638       -1    2857
...         ...   ...     ...     ...      ...     ...
866    42855610  1996       1   42944       -1    4513
5396   50640149  1813      -1    1030       -1    6370
5267   29250865  2393      -1    3041       -1    2412
2375  138103923   714      -1    5700       -1    1069
4556   74642040  1435      -1  155974       -1    5103

[656 rows x 6 columns]

In [136]:
unlabeled

id  days  mature  views  partner  new_id
4978   81421457  1350       1  79434       -1    2883
4177  113836617   991       1   1420       -1     215
283   179872216   344      -1   1767       -1    3452
3505  134223670   754      -1  83242        1    2363
6224   43536199  1975       1   1612       -1    2831
...         ...   ...     ...    ...      ...     ...
156    93029163  1222       1  71985       -1     301
4494   24198897  2592      -1    450       -1    4279
4241  101122786  1138      -1  21715       -1     272
3801   36817410  2163       1   2272       -1     993
373   132294537   787      -1   6146       -1    4020

[5895 rows x 6 columns]

In [137]:
import numpy as np

def label_propagation(G, Yl, max_iter=100, tol=1e-4):
    """
    Label propagation algorithm for graph G with initial labels Yl.

    Parameters:
    - G: numpy array, adjacency matrix of the graph.
    - Yl: numpy array, initial labels for some of the nodes.
    - max_iter: int, maximum number of iterations.
    - tol: float, convergence threshold.

    Returns:
    - Y: numpy array, final labels for all nodes.
    """
    D = np.diagflat(np.sum(G, axis=1)[0:,])
    

    # Compute the transition matrix.
    P = np.linalg.inv(D) @ G

    # Initialize the label vector.
    Y = np.zeros(G.shape[0])
    Y[Yl[:, 0]] = Yl[:, 1]

    # Iterate until convergence.
    for i in range(max_iter):
        Y_new = P @ Y
        Y_new[Yl[:, 0]] = Y[Yl[:, 0]]
        if np.linalg.norm(Y_new - Y) < tol:
            break
        Y = Y_new

    return Y


In [138]:
Yl=[]
for _,row in labeled.iterrows():
    Yl.append([row["new_id"],row["mature"]])

Yl_unlab=[]
for _,row in unlabeled.iterrows():
    Yl_unlab.append([row["new_id"],row["mature"]])

In [139]:
Yl=np.array(Yl)

Yl_unlab=np.array(Yl_unlab)

Y=label_propagation(mat,Yl)


In [140]:
correct=0
negpred=0
pospred=0
for i in range(0,Yl_unlab.shape[0]):
    ind=Yl_unlab[i,0]
    truelabel=Yl_unlab[i,1]
    if Y[ind]>=0 and  truelabel>=0:
        correct+=1
        pospred+=1
    if Y[ind]<=0 and  truelabel<=0:
        correct+=1
        negpred+=1

In [141]:
correct/Yl_unlab.shape[0]

0.6273112807463953

In [142]:
negpred

3697

In [143]:
pospred

1

In [145]:
unlabeled["mature"].value_counts()

-1    3697
 1    2198
Name: mature, dtype: int64

In [146]:
labeled["mature"].value_counts()

-1    438
 1    218
Name: mature, dtype: int64

In [32]:
max_iter=10000

In [33]:
tol=1e-4

In [34]:
mat

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [35]:
G=mat

In [36]:
D = np.diagflat(np.sum(mat, axis=1)[0:,])
print(D)

# Compute the transition matrix.
P = np.linalg.inv(D) @ mat

# Initialize the label vector.
Y = np.zeros(mat.shape[0])
Y[Yl[:, 0]] = Yl[:, 1]

# Iterate until convergence.
for i in range(max_iter):
    Y_new = P @ Y
    Y_new[Yl[:, 0]] = Y[Yl[:, 0]]
    if np.linalg.norm(Y_new - Y) < tol:
        break
    Y = Y_new

[[11  0  0 ...  0  0  0]
 [ 0 29  0 ...  0  0  0]
 [ 0  0 21 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  1]]


In [37]:
import numpy as np
from sklearn.base import clone

def iterative_classification(G, Yl, clf, max_iter=100, tol=1e-4):
    """
    Iterative classification algorithm for graph G with initial labels Yl.

    Parameters:
    - G: numpy array, adjacency matrix of the graph.
    - Yl: numpy array, initial labels for some of the nodes.
    - clf: scikit-learn classifier object, classifier to use for classification.
    - max_iter: int, maximum number of iterations.
    - tol: float, convergence threshold.

    Returns:
    - Y: numpy array, final labels for all nodes.
    """
    D = np.diagflat(np.sum(G, axis=1)[0:,])
    
    # Compute the transition matrix.
    P = np.linalg.inv(D) @ G

    # Initialize the label vector.
    Y = np.zeros(G.shape[0])
    Y[Yl[:, 0]] = Yl[:, 1]

    # Initialize feature matrix.
    X = np.zeros((G.shape[0], clf.n_features_))
    X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])

    # Iterate until convergence.
    for i in range(max_iter):
        # Train classifier on labeled nodes.
        clf.fit(X[Yl[:, 0]], Y[Yl[:, 0]])
        
        # Predict labels for unlabeled nodes.
        Y_new = clf.predict(X[Vu, :])
        
        # Update labeled nodes.
        Y[Yl[:, 0]] = Yl[:, 1]
        X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])
        
        # Check for convergence.
        if np.linalg.norm(Y_new - Y[Vu]) < tol:
            break
        
        # Add new labeled nodes.
        new_labeled = np.vstack((Vu[Y_new != Y[Vu]], Y_new[Y_new != Y[Vu]])).T
        Yl = np.vstack((Yl, new_labeled))
        
        # Update feature matrix.
        X[new_labeled[:, 0]] = clf.transform(G[new_labeled[:, 0], :])
        
        # Update labeled and unlabeled node sets.
        Vl = np.unique(Yl[:, 0])
        Vu = np.setdiff1d(range(G.shape[0]), Vl)
    
    return Y


In [38]:
label_to_predict=labeled["partner"]

label_to_test=unlabeled["partner"]

train=labeled.drop("partner",axis=1)

test=unlabeled.drop("partner",axis=1)

In [39]:



param_grid = {
    'max_depth': [2, 4, 6, 8],
    'n_estimators': [50, 100, 200, 400]
}

clf = RandomForestClassifier(random_state=0)

grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, n_jobs=-1,scoring="recall")
grid_search.fit(train, label_to_predict)

print("Best hyperparameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)


Best hyperparameters: {'max_depth': 8, 'n_estimators': 200}
Best score: 0.7096634615384616


In [40]:
clf = RandomForestClassifier(max_depth=8,n_estimators=100)

In [41]:
iterative_classification(G,Yl,clf)

AttributeError: 'RandomForestClassifier' object has no attribute 'n_features_'

In [ ]:
# Initialize feature matrix.
X = np.zeros((G.shape[0], clf.n_classes_))
X[Yl[:, 0]] = clf.predict_proba(G[Yl[:, 0], :])

# Iterate until convergence.
for i in range(max_iter):
    # Train classifier on labeled nodes.
    clf.fit(X[Yl[:, 0]], Y[Yl[:, 0]])
    
    # Predict probability estimates for unlabeled nodes.
    Y_proba = clf.predict_proba(G[Vu, :])
    
    # Update labeled and unlabeled node features.
    X[Yl[:, 0]] = clf.predict_proba(G[Yl[:, 0], :])
    X[Vu] = Y_proba
    
    # Check for convergence.
    if np.linalg.norm(Y_proba - Y[Vu]) < tol:
        break
    
    # Add new labeled nodes.
    new_labeled = np.vstack((Vu[Y_proba.argmax(axis=1) != Y[Vu]], Y_proba[Y_proba.argmax(axis=1) != Y[Vu]])).T
    Yl = np.vstack((Yl, new_labeled))
    
    # Update labeled and unlabeled node sets.
    Vl = np.unique(Yl[:, 0])
    Vu = np.setdiff1d(range(G.shape[0]), Vl)


In [ ]:
D = np.diagflat(np.sum(G, axis=1)[0:,])

# Compute the transition matrix.
P = np.linalg.inv(D) @ G

# Initialize the label vector.
Y = np.zeros(G.shape[0])
Y[Yl[:, 0]] = Yl[:, 1]

# Initialize feature matrix.
X = np.zeros((G.shape[0], clf.n_features_))
X[Yl[:, 0]] = clf.predict_proba(G[Yl[:, 0], :]) # Use predict_proba to get class probabilities, then convert to feature matrix
X = np.concatenate([1 - X, X], axis=1) # Convert class probabilities to one-hot encoding

# Iterate until convergence.
for i in range(max_iter):
    # Train classifier on labeled nodes.
    clf.fit(X[Yl[:, 0]], Y[Yl[:, 0]])

    # Predict labels for unlabeled nodes.
    Y_new = clf.predict(X[Vu, :])

    # Update labeled nodes.
    Y[Yl[:, 0]] = Yl[:, 1]
    X[Yl[:, 0]] = clf.predict_proba(G[Yl[:, 0], :]) # Use predict_proba to get class probabilities, then convert to feature matrix
    X = np.concatenate([1 - X, X], axis=1) # Convert class probabilities to one-hot encoding

    # Check for convergence.
    if np.linalg.norm(Y_new - Y[Vu]) < tol:
        break

    # Add new labeled nodes.
    new_labeled = np.vstack((Vu[Y_new != Y[Vu]], Y_new[Y_new != Y[Vu]])).T
    Yl = np.vstack((Yl, new_labeled))

    # Update feature matrix.
    X[new_labeled[:, 0]] = clf.predict_proba(G[new_labeled[:, 0], :]) # Use predict_proba to get class probabilities, then convert to feature matrix
    X = np.concatenate([1 - X, X], axis=1) # Convert class probabilities to one-hot encoding

    # Update labeled and unlabeled node sets.
    Vl = np

In [ ]:
    D = np.diagflat(np.sum(G, axis=1)[0:,])
    
    # Compute the transition matrix.
    P = np.linalg.inv(D) @ G

    # Initialize the label vector.
    Y = np.zeros(G.shape[0])
    Y[Yl[:, 0]] = Yl[:, 1]

    # Initialize feature matrix.
    X = np.zeros((G.shape[0], clf.n_features_))
    X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])

    # Iterate until convergence.
    for i in range(max_iter):
        # Train classifier on labeled nodes.
        clf.fit(X[Yl[:, 0]], Y[Yl[:, 0]])
        
        # Predict labels for unlabeled nodes.
        Y_new = clf.predict(X[Vu, :])
        
        # Update labeled nodes.
        Y[Yl[:, 0]] = Yl[:, 1]
        X[Yl[:, 0]] = clf.transform(G[Yl[:, 0], :])
        
        # Check for convergence.
        if np.linalg.norm(Y_new - Y[Vu]) < tol:
            break
        
        # Add new labeled nodes.
        new_labeled = np.vstack((Vu[Y_new != Y[Vu]], Y_new[Y_new != Y[Vu]])).T
        Yl = np.vstack((Yl, new_labeled))
        
        # Update feature matrix.
        X[new_labeled[:, 0]] = clf.transform(G[new_labeled[:, 0], :])
        
        # Update labeled and unlabeled node sets.
        Vl = np.unique(Yl[:, 0])
        Vu = np.setdiff1d(range(G.shape[0]), Vl)
    

In [ ]:
X.shape

In [ ]:
clf.fit(train,label_to_predict)

In [ ]:
pred=clf.predict(test)

In [ ]:
pred

In [ ]:
from sklearn.metrics import accuracy_score,recall_score

print(accuracy_score(label_to_test, pred))
print(recall_score(label_to_test,pred))




In [ ]:
unlabeled["partner"].value_counts()

In [ ]:
pd.DataFrame(pred).value_counts()

In [ ]:
with open('../facebook/1684.edges', 'r') as f:
    edges = [tuple(map(int, line.strip().split())) for line in f]


In [ ]:
edges

In [ ]:
Graph.shape

In [ ]:
Graph

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

# Create a random feature matrix and label vector
X = np.random.rand(100, 10)
y = np.random.randint(0, 2, size=100)

# Create a random forest classifier and fit it to the data
clf = RandomForestClassifier()
clf.fit(X, y)

# Compute the feature importances
importances = clf.feature_importances_


In [ ]:
X.shape

In [ ]:
importances

In [ ]:
import numpy as np

# G is the graph, Y is the label vector
# A is the multiclass learning algorithm

# Initialize the classifier
X = np.zeros((len(G.nodes), num_features))  # construct feature matrix
clf = A(X, Y)  # initialize the classifier

# Iterative classification
for i in range(num_iterations):
    # Generate ordering O over nodes of G
    nodes = list(G.nodes)
    np.random.shuffle(nodes)  # shuffle nodes randomly
    
    # Iterate over nodes in O
    for node in nodes:
        # Compute conditional probabilities for each label
        xi = np.concatenate([node_features[node], neighbor_features[node]])  # construct feature vector for node
        probas = clf.predict_proba(xi.reshape(1, -1))[0]  # compute probability vector
        
        # Sample label for node
        label = np.random.choice(labels, p=probas)  # sample label from probability distribution
        
        # Submit training example to A
        neighborhood = G.neighbors(node)  # get neighbors of node
        neighbor_features = [node_features[n] for n in neighborhood]  # get feature vectors for neighbors
        X_node = np.concatenate([xi, neighbor_features], axis=0)  # construct feature matrix for node and its neighbors
        Y_node = label  # label for node
        clf.partial_fit(X_node.reshape(1, -1), [Y_node])  # update classifier with new training example


In [ ]:
#NOUVEAU CODE

In [ ]:
### Premier test : 10% des noeuds labélisés, choix des noeuds random

In [ ]:
#Comment on choisis nos points de départs : il y a un vrai travaille à faire la dessus.

In [260]:
target=pd.read_csv("./twitch/FR/musae_FR_target.csv")

target["mature"]=target["mature"].apply(binary)

target["partner"]=target["partner"].apply(binary)

In [261]:

# load JSON data from file
with open(graph_path, 'r') as f:
    data = json.load(f)

# create new NetworkX graph
G = nx.Graph()


G = nx.from_dict_of_lists(data)

# visualize the graph
#nx.draw(G, with_labels=True)

mat=nx.adjacency_matrix(G).toarray()

In [262]:
nx.degree_centrality(G)

{'3032': 0.001246741471154936,
 '4032': 0.0032868638784993767,
 '3945': 0.0023801428085685142,
 '949': 0.003740224413464808,
 '5137': 0.002040122407344441,
 '400': 0.0017001020061203672,
 '1803': 0.001813442139861725,
 '2468': 0.0058936869545506065,
 '289': 0.0013600816048962938,
 '5687': 0.002040122407344441,
 '2811': 0.0015867618723790094,
 '1689': 0.001813442139861725,
 '6077': 0.001813442139861725,
 '3324': 0.0019267822736030828,
 '6357': 0.0014734217386376516,
 '5905': 0.0023801428085685142,
 '5571': 0.0021534625410857986,
 '1968': 0.002040122407344441,
 '3636': 0.0014734217386376516,
 '1769': 0.0017001020061203672,
 '349': 0.002040122407344441,
 '1983': 0.003740224413464808,
 '3867': 0.002040122407344441,
 '1234': 0.0019267822736030828,
 '137': 0.001813442139861725,
 '5310': 0.003173523744758019,
 '4677': 0.002040122407344441,
 '4619': 0.0029468434772753033,
 '2481': 0.0014734217386376516,
 '1508': 0.0017001020061203672,
 '2901': 0.00260682307605123,
 '1068': 0.002266802674827156

In [263]:

# compute degree centrality for each node
degree_centrality = nx.degree_centrality(G)

# sort nodes by degree centrality
sorted_nodes = sorted(degree_centrality, key=degree_centrality.get, reverse=True)

In [264]:
target

id  days  mature  views  partner  new_id
0     150417538   577       1    775       -1    4867
1     125723704   861       1   2585       -1    3692
2     155971814   523      -1   1566       -1    3816
3      35832890  2234      -1   9713       -1     416
4      46787750  1896       1  44529       -1    4502
...         ...   ...     ...    ...      ...     ...
6546   29196284  2061      -1   3822       -1    6546
6547  124327806   880       1  30313       -1    2392
6548  144229380   640       1   5022       -1     391
6549  131423064   736      -1   2658       -1    2793
6550   45419243  1929       1   3743       -1    1092

[6551 rows x 6 columns]

In [265]:
top_central = target[target["new_id"].isin(sorted_nodes[0:200])]

In [266]:
top_central

id  days  mature   views  partner  new_id
16     37799198  2154      -1  117104       -1    3152
28     71914876  1478       1   97104        1    2184
45     43907647  1964       1    4340       -1     308
47    152705416   547      -1    5514       -1    2611
148   184696828   308       1   10328       -1    2476
...         ...   ...     ...     ...      ...     ...
6285  114757037   982      -1     749       -1    1387
6330   31176783  1995      -1    4986       -1    1796
6448   46402303  1909      -1    1815       -1    1102
6476  102520144  1119       1  103397       -1    2168
6530   37444727  2162      -1    2129       -1    2914

[197 rows x 6 columns]

In [267]:
unlabeled,labeled=top_central,target.drop(top_central.index)

In [268]:
unlabeled

id  days  mature   views  partner  new_id
16     37799198  2154      -1  117104       -1    3152
28     71914876  1478       1   97104        1    2184
45     43907647  1964       1    4340       -1     308
47    152705416   547      -1    5514       -1    2611
148   184696828   308       1   10328       -1    2476
...         ...   ...     ...     ...      ...     ...
6285  114757037   982      -1     749       -1    1387
6330   31176783  1995      -1    4986       -1    1796
6448   46402303  1909      -1    1815       -1    1102
6476  102520144  1119       1  103397       -1    2168
6530   37444727  2162      -1    2129       -1    2914

[197 rows x 6 columns]

In [269]:
labeled

id  days  mature  views  partner  new_id
0     150417538   577       1    775       -1    4867
1     125723704   861       1   2585       -1    3692
2     155971814   523      -1   1566       -1    3816
3      35832890  2234      -1   9713       -1     416
4      46787750  1896       1  44529       -1    4502
...         ...   ...     ...    ...      ...     ...
6546   29196284  2061      -1   3822       -1    6546
6547  124327806   880       1  30313       -1    2392
6548  144229380   640       1   5022       -1     391
6549  131423064   736      -1   2658       -1    2793
6550   45419243  1929       1   3743       -1    1092

[6354 rows x 6 columns]

In [278]:
unlabeled,labeled=train_test_split(target[["days","views","mature","new_id","mature"]],test_size=0.10)

In [279]:
labeled,unlabeled=top_central,target.drop(top_central.index)

In [272]:
print(labeled["mature"].value_counts())
print(unlabeled["mature"].value_counts())

-1    124
 1     73
Name: mature, dtype: int64
-1    4011
 1    2343
Name: mature, dtype: int64


In [281]:
from sklearn.metrics import *

#G is the complete graph
#train_temp,test_temp=train_test_split(unlabeled)

while unlabeled.shape[0]>0:

    Y_temp=labeled["partner"]
    graph_lab=G.subgraph([n for n in labeled["new_id"]])
    
    clf = RandomForestClassifier(random_state=0,max_depth=8,n_estimators=100)

    clf.fit(labeled.drop(columns=["partner","new_id"]),Y_temp)

    nodes_with_edge_to_subgraph = [n for n in G.nodes() if n not in graph_lab and any([n in G.neighbors(subgraph_node) for subgraph_node in graph_lab])]
    new_ids=[int(n) for n in nodes_with_edge_to_subgraph]

    to_label = unlabeled[unlabeled["new_id"].isin(new_ids)]

    y_test=to_label["partner"]

    y_pred=clf.predict(to_label.drop(columns=["partner","new_id"]))
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    to_label["partner"]=y_pred

    print("accuracy=",accuracy,"precision=",precision,"recall=",recall)

    unlabeled = unlabeled.drop(to_label.index)
    labeled = pd.concat([labeled, to_label], axis=0)

accuracy= 0.9705650873603022 precision= 0.9687787150131377 recall= 0.9705650873603022


In [276]:
labeled.set_index('new_id', inplace=True,drop=False)
target.set_index('new_id', inplace=True,drop=False,)
labeled.sort_index(inplace=True)
target.sort_index(inplace=True)

In [282]:
accuracy = accuracy_score(target["partner"], labeled["partner"])
precision = precision_score(target["partner"], labeled["partner"], average='weighted')
recall = recall_score(target["partner"], labeled["partner"], average='weighted')
#f1 = f1_score(target["partner"], labeled["partner"], average='weighted')

print("accuracy=",accuracy,"precision=",precision,"recall=",recall)

ValueError: Found input variables with inconsistent numbers of samples: [6551, 6550]

In [227]:
target.loc[target["mature"]!=labeled["mature"]]

id  days  mature   views  partner  new_id
new_id                                                  
83      193986809   254       1    8527       -1      83
213      39862851  2078       1   16106       -1     213
308      43907647  1964       1    4340       -1     308
316      93356875  1217      -1   35675       -1     316
318      87114575  1287       1   12808       -1     318
...           ...   ...     ...     ...      ...     ...
3023     74538376  1437      -1   55007       -1    3023
3040     35954085  2225       1   26039       -1    3040
3048    107863484  1050      -1   13167       -1    3048
3084     24459863  2597       1  871102        1    3084
3164    121069264   831       1     883       -1    3164

[70 rows x 6 columns]

In [228]:
labeled.loc[target["mature"]!=labeled["mature"]]

id  days  mature   views  partner  new_id
new_id                                                  
83      193986809   254      -1    8527       -1      83
213      39862851  2078      -1   16106       -1     213
308      43907647  1964      -1    4340       -1     308
316      93356875  1217       1   35675       -1     316
318      87114575  1287      -1   12808       -1     318
...           ...   ...     ...     ...      ...     ...
3023     74538376  1437       1   55007       -1    3023
3040     35954085  2225      -1   26039       -1    3040
3048    107863484  1050       1   13167       -1    3048
3084     24459863  2597      -1  871102        1    3084
3164    121069264   831      -1     883       -1    3164

[70 rows x 6 columns]

In [8]:
labeled["mature"].value_counts()

False    6523
True       28
Name: mature, dtype: int64

In [9]:
target["mature"].value_counts()

False    4135
True     2416
Name: mature, dtype: int64

In [229]:
graph_path_DE="./twitch/DE/musae_DE.json"

In [230]:
targetDE=pd.read_csv("./twitch/DE/musae_DE_target.csv")

In [239]:

# load JSON data from file
with open(graph_path_DE, 'r') as f:
    dataDE = json.load(f)

# create new NetworkX graph
G_DE = nx.Graph()

G_DE = nx.from_dict_of_lists(dataDE)

In [240]:
targetDE["mature"]=targetDE["mature"].apply(binary)

targetDE["partner"]=targetDE["partner"].apply(binary)

In [241]:

# compute degree centrality for each node
degree_centrality = nx.degree_centrality(G_DE)

# sort nodes by degree centrality
sorted_nodes = sorted(degree_centrality, key=degree_centrality.get, reverse=True)

In [242]:
sorted_nodes

[920,
 224,
 3097,
 569,
 861,
 653,
 2424,
 2737,
 276,
 2645,
 810,
 2384,
 2362,
 1147,
 2501,
 2549,
 257,
 2524,
 83,
 2928,
 635,
 846,
 706,
 3054,
 436,
 139,
 440,
 1525,
 588,
 1213,
 1796,
 3152,
 2936,
 1656,
 751,
 1108,
 3044,
 502,
 803,
 802,
 928,
 400,
 2168,
 2153,
 48,
 2912,
 2063,
 3164,
 2323,
 1907,
 768,
 2661,
 1028,
 704,
 1548,
 69,
 1649,
 608,
 1387,
 1612,
 2409,
 1085,
 1245,
 1764,
 3057,
 1013,
 2184,
 318,
 2764,
 1530,
 2814,
 119,
 1144,
 1607,
 2327,
 1761,
 929,
 760,
 1195,
 964,
 152,
 2734,
 2243,
 1391,
 2282,
 821,
 2204,
 1113,
 2484,
 859,
 1570,
 308,
 1222,
 2668,
 2510,
 2770,
 1505,
 1234,
 213,
 1895,
 1047,
 1762,
 2902,
 1431,
 1889,
 2677,
 509,
 1948,
 2479,
 1540,
 2534,
 1951,
 2178,
 1417,
 757,
 1644,
 1535,
 515,
 2656,
 2130,
 2248,
 2060,
 3061,
 433,
 2846,
 1726,
 1968,
 855,
 911,
 454,
 1521,
 2446,
 421,
 763,
 1191,
 2223,
 3019,
 2665,
 294,
 1550,
 839,
 2724,
 329,
 2962,
 2918,
 89,
 210,
 2347,
 3023,
 390,
 1362,

In [243]:
top_central = targetDE[targetDE["new_id"].isin(sorted_nodes[0:200])]

In [247]:
labeled,unlabeled=top_central,targetDE.drop(top_central.index)

In [248]:
labeled

id  days  mature  views  partner  new_id
125    99161442  1156       1  49652       -1    3097
134    95830875  1189       1  11586       -1    2912
144    55464534  1719       1   7203       -1    2661
164    97600154  1170       1   9319       -1     378
173   125245545   868       1   1460       -1    3054
...         ...   ...     ...    ...      ...     ...
9240   65554000  1556      -1   9155       -1     920
9241   44253989  1936      -1   4630       -1     454
9286   41631897  2007       1   4358       -1      89
9385   73110185  1457      -1   5608       -1    2709
9479  119769965   930       1   2526       -1    1656

[200 rows x 6 columns]

In [249]:
unlabeled

id  days  mature     views  partner  new_id
0      37905227  2149       1    162078       -1    5079
1      63102384  1574       1      1370       -1    4281
2     109414094  1034       1      6043       -1     992
3      84163849  1319       1     94298        1    9021
4      38240837  2137       1      2323       -1     330
...         ...   ...     ...       ...      ...     ...
9493  123101102   895       1       128       -1    4572
9494   40627165  2001      -1        44       -1    6355
9495   50643307  1784       1      2038       -1     206
9496   38810779  2114      -1       449       -1    7695
9497   58351323  1680      -1  10638954        1    4451

[9298 rows x 6 columns]